### ISSUE TITLE
random_image is not defined 

### ISSUE THREAD

**Issue by REXXAR2162** [Ziad-o-Yusef/breast-cancer-detection-using-cnn-DL-#1]
Hello, I am trying to run your code for our project with the same goal except we want to use transfer learning. We faced with an error in a cell
`data.target = data.target.astype(np.int)
random_image_path = np.random.choice(data[data.target ==0].index, size=1, replace=False,)
path =os.path.join(all_rays_dir,data.loc[random_image[0], 'image_id'])
image = mpimg.imread(path)
plt.imshow(image)`

where we get this error

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-e92774561615>", line 3, in <module>
    path =os.path.join(all_rays_dir,data.loc[random_image[0], 'image_id'])
NameError: name 'random_image' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.estimator'
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-e92774561615>", line 3, in <module>
    path =os.path.join(all_rays_dir,data.loc[random_image[0], 'image_id'])
NameError: name 'random_image' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3360, in run_code
    self.showtraceback(running_compiled_code=True)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1193, in structured_traceback
    tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.estimator'
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-e92774561615>", line 3, in <module>
    path =os.path.join(all_rays_dir,data.loc[random_image[0], 'image_id'])
NameError: name 'random_image' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3360, in run_code
    self.showtraceback(running_compiled_code=True)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1193, in structured_traceback
    tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3072, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 3282, in run_ast_nodes
    self.showtraceback()
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2047, in showtraceback
    value, tb, tb_offset=tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1436, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1336, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1211, in structured_traceback
    chained_exceptions_tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1150, in format_exception_as_a_whole
    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 451, in find_recursion
    return len(records), 0
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\interactiveshell.py", line 2044, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 1169, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\inspect.py", line 733, in getmodule
    if ismodule(module) and hasattr(module, '__file__'):
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "F:\ProgramData\Anaconda3\envs\breast_cancer_classif\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_core.estimator'

The basic gist is that random_image is not defined. We would appreciate your help with future errors too since we are not good at programming and would require assistance. Waiting for your reply.

**Comment by REXXAR2162** [comment]
I've changed `random_image_path` to `random_image` which has seemed to work. Is this right?
